version: "3.8"
services:
  influx:
    image: influxdb:1.7.9
    environment:
      INFLUXDB_DB:  "ncmetering"
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "supersecretpassword"
      INFLUXDB_USER: "agent"
      INFLUXDB_USER_PASSWORD: "smith"
      INFLUXDB_REPORTING_DISABLED: "true"
    ports:
      - 8086:8086
    volumes:
      - dbdata:/var/lib/influxdb
      - ./iql/nautilus-cloud-metering.iql:/docker-entrypoint-initdb.d/01-initdb.iql
    networks:
      - ncm-net

  nginx:
    image: nginx:latest
    depends_on:
      - influx
      - metering-agent
    networks:
      - ncm-net
    ports:
      - 9090:9090
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ulimits:
      nproc: 65535
      nofile: 165535

  metering-agent:
    image: ncm-agent-api
    depends_on:
      - influx
    networks:
      - ncm-net
    ports:
      - 3050:3050
    build:
      context: ./
      target: ncm-agent-api

  metering-api:
    image: ncm-metering-api
    depends_on:
      - influx
    networks:
      - ncm-net
    ports:
      - 8080:8080
    build:
      context: ./
      target: ncm-metering-api

networks:
  ncm-net:

volumes:
  dbdata: