version: "3.7"
services:
  agent:
    build:
      context: .
      dockerfile: docker/loadtest/Dockerfile
    image: ncmetering:loadtest
    ports:
      - 9090:9090
    networks:
      - loadtest
    depends_on:
      - influx
  influx:
    image: influxdb:1.7.9
    environment:
      INFLUXDB_DB:  "ncmetering"
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "supersecretpassword"
      INFLUXDB_USER: "agent"
      INFLUXDB_USER_PASSWORD: "smith"
    ports:
      - 8086:8086
    volumes:
      - dbdata:/var/lib/influxdb
      - ./iql/nautilus-cloud-metering.iql:/docker-entrypoint-initdb.d/01-initdb.iql
    networks:
      - loadtest


networks:
  loadtest:

volumes:
  dbdata:
