config:
  target: 'http://localhost:9090'
  plugins:
    expect: {}
  phases:
    - duration: 5
      arrivalRate: 50
      name: "Constant Load"
scenarios:
  - name: "Authorized User"
    weight: 2
    flow:
      - get:
          url: "/nginx_status"
          headers:
            apiKey: 'engage'
        expect:
          - statusCode: 200

  - name: "Un-Authorized User"
    weight: 1
    flow:
      - get:
          url: "/nginx_status/head"
          headers:
            apiKey: 'This-is-an-invalid-key'
        expect:
          - statusCode: 403
  - name: "I didn't read the docs User"
    weight: 1
    flow:
      - get:
          url: "/nginx_status/tail"
          headers:
            nottheapikeyheader: 'Some random header'
        expect:
          - statusCode: 403
